CREATE TABLE "users"(
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "username" TEXT NOT NULL UNIQUE CHECK (LENGTH(username) BETWEEN 1 AND 20),
  "password" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "categories"(
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "user_id" INTEGER NOT NULL REFERENCES "users"("id"),
  "name" TEXT NOT NULL CHECK (LENGTH(name) BETWEEN 1 AND 20),
  "color" TEXT NOT NULL CHECK (LENGTH(color) BETWEEN 7 AND 9),
  "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "snippets"(
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "user_id" INTEGER NOT NULL REFERENCES "users"("id"),
  "title" TEXT NOT NULL CHECK (LENGTH(title) BETWEEN 1 AND 20),
  "description" TEXT CHECK (LENGTH(description) BETWEEN 0 AND 50),
  "content" TEXT NOT NULL CHECK (LENGTH(content) BETWEEN 1 AND 1500),
  "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "snippets_categories"(
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "category_id" INTEGER NOT NULL REFERENCES "categories"("id"),
  "snippet_id" INTEGER NOT NULL REFERENCES "snippets"("id"),
  "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);